---
collections:
  - name: infra.aap_configuration
    version: ">=3.0.0"
  - name: awx.awx
    version: ">=24.0.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: ansible.platform
  - name: ansible.hub
  - name: ansible.controller
    version: ">=4.6.0"
  - name: ansible.eda
