---
# Redirection flags for infra.aap_configuration
aap_configuration_use_awx_collection: true
infra_aap_configuration_use_awx_collection: true
controller_configuration_use_awx_collection: true

# Declarative AAP Configuration Data
controller_organizations:
  - name: "Default"
    description: "Primary Enterprise Organization"

controller_credentials:
  - name: "Production SSH Key"
    description: "Machine SSH Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      username: "ansible"
      ssh_key_data: "{{ vault_ssh_private_key }}"

controller_projects:
  - name: "GitOps Application Configs"
    description: "Managed via GitOps IaC Pipeline"
    scm_type: "git"
    scm_url: "https://github.com/jopaik/aap-gitops-lac.git"
    scm_branch: "main"
    organization: "Default"
    wait: false # Prevents pipeline timeouts while cloning git repos

controller_inventories:
  - name: "Multi-DC Production Inventory"
    description: "Production Inventory spanning DC1 and DC2"
    organization: "Default"
    hosts:
      dc1_host_1:
        ansible_host: "127.0.0.1"
      dc1_host_2:
        ansible_host: "127.0.0.1"
      dc2_host_3:
        ansible_host: "127.0.0.1"
      dc2_host_4:
        ansible_host: "127.0.0.1"
    groups:
      dc1:
        hosts:
          - dc1_host_1
          - dc1_host_2
      dc2:
        hosts:
          - dc2_host_3
          - dc2_host_4

# Use controller_templates for infra.aap_configuration
controller_templates:
  - name: "Deploy Workload Job"
    project: "GitOps Application Configs"
    playbook: "playbooks/demorun.yml"
    inventory: "Multi-DC Production Inventory"
    job_type: "run"