---
aap_configuration_use_awx_collection: false
infra_aap_configuration_use_awx_collection: false
controller_configuration_use_awx_collection: false

aap_instances:
  - name: "AAP-Platform-Alpha"
    host: "{{ vault_aap_gateway_a_url }}"
    username: "admin"
    password: "{{ vault_aap_gateway_a_password }}"
    validate_certs: false
  - name: "AAP-Platform-Beta"
    host: "{{ vault_aap_gateway_b_url }}"
    username: "admin"
    password: "{{ vault_aap_gateway_b_password }}"
    validate_certs: false

controller_organizations:
  - name: "Default"
    description: "Primary Enterprise Organization"

controller_credentials:
  - name: "Production SSH Key"
    description: "Machine Password Credential"
    credential_type: "Machine"
    organization: "Default"
    inputs:
      username: "ansible"
      password: "{{ vault_aap_gateway_a_password }}"

controller_projects:
  - name: "GitOps Application Configs"
    description: "Managed via GitOps IaC Pipeline"
    scm_type: "git"
    scm_url: "https://github.com/jopaik/aap-gitops-lac.git"
    scm_branch: "main"
    scm_update_on_launch: true
    organization: "Default"
    wait: true

controller_inventories:
  - name: "Multi-DC Production Inventory"
    description: "Production Inventory spanning DC1 and DC2"
    organization: "Default"

controller_hosts:
  - name: "dc1_host_1"
    inventory: "Multi-DC Production Inventory"
    variables:
      ansible_host: "127.0.0.1"
  - name: "dc1_host_2"
    inventory: "Multi-DC Production Inventory"
    variables:
      ansible_host: "127.0.0.1"
  - name: "dc2_host_3"
    inventory: "Multi-DC Production Inventory"
    variables:
      ansible_host: "127.0.0.1"
  - name: "dc2_host_4"
    inventory: "Multi-DC Production Inventory"
    variables:
      ansible_host: "127.0.0.1"

controller_groups:
  - name: "dc1"
    inventory: "Multi-DC Production Inventory"
    hosts:
      - "dc1_host_1"
      - "dc1_host_2"
  - name: "dc2"
    inventory: "Multi-DC Production Inventory"
    hosts:
      - "dc2_host_3"
      - "dc2_host_4"

controller_templates:
  - name: "Deploy Workload Job"
    project: "GitOps Application Configs"
    playbook: "playbooks/demorun.yml"
    inventory: "Multi-DC Production Inventory"
    job_type: "run"