---
- name: "Configure AAP Platform Node: {{ current_aap.name }}"
  block:
    - name: Apply AAP Controller Configurations
      ansible.builtin.include_role:
        name: infra.aap_configuration.dispatch
      vars:
        aap_configuration_dispatcher_roles:
          - role: organizations
            var: controller_organizations
            tags: organizations
          - role: credentials
            var: controller_credentials
            tags: credentials
          - role: projects
            var: controller_projects
            tags: projects
          - role: inventories
            var: controller_inventories
            tags: inventories
          - role: job_templates
            var: controller_templates
            tags: job_templates

        controller_hostname: "{{ current_aap.host }}"
        controller_username: "{{ current_aap.username }}"
        controller_password: "{{ current_aap.password }}"
        controller_validate_certs: "{{ current_aap.validate_certs }}"