---
- name: Demo Workload Run
  hosts: all
  gather_facts: false
  tasks:
    - name: Output Execution Message
      ansible.builtin.debug:
        msg: "Successfully executed workload demo run on {{ inventory_hostname }}"