name: AAP 2.6 Workload Dispatch (Deploy Branch)

on:
  push:
    branches: [ "deploy" ]
  workflow_dispatch:

jobs:
  dispatch-round-robin:
    runs-on: ubuntu-latest
    container:
      image: quay.io/jopaik/aap-runner:jp1
      credentials:
        username: ${{ secrets.QUAY_USERNAME }}
        password: ${{ secrets.QUAY_PASSWORD }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Create Vault Password File
        run: |
          echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass
          chmod 600 .vault_pass

      - name: Round-Robin Job Dispatch
        run: |
          ansible-playbook playbooks/dispatch_round_robin.yml --vault-password-file .vault_pass
        env:
          ANSIBLE_NO_LOG: "False"
          
      - name: Clean up Vault Password File
        if: always()
        run: rm -f .vault_pass